import csv
import re
from datetime import datetime
from io import StringIO

from flask import Response

from app.services.settings_service import SettingsService


def _title_case(value):
    text = re.sub(r"[_\s]+", " ", str(value or "").strip())
    return text.title()


def _safe_filename_part(value):
    return re.sub(r"[^A-Za-z0-9_-]+", "_", str(value or "").strip()).strip("_") or "export"


def sanitize_cell(value):
    if value is None:
        return ""
    if isinstance(value, datetime):
        text = format_export_datetime(value)
    elif isinstance(value, bool):
        text = "Yes" if value else "No"
    else:
        text = str(value)
    text = text.strip()
    if text and text[0] in ("=", "+", "-", "@", "\t", "\r"):
        text = "'" + text
    return text


def format_export_datetime(value=None):
    value = value or datetime.utcnow()
    try:
        return value.strftime("%b %d, %Y at %#I:%M %p")
    except ValueError:
        return value.strftime("%b %d, %Y at %-I:%M %p")


def build_csv_response(export_type, actor, rows, columns, filename=None, extra_metadata=None):
    settings = SettingsService.get_settings()
    platform_name = getattr(settings, "platform_name", None) or "Exam System"
    actor_name = getattr(actor, "name", None) or getattr(actor, "username", None) or "System"
    actor_role = getattr(actor, "role", None) or "system"
    now = datetime.utcnow()
    safe_export_type = _safe_filename_part(export_type)
    filename = filename or f"{_safe_filename_part(platform_name)}_{safe_export_type}_{now.strftime('%Y%m%d')}.csv"

    output = StringIO()
    output.write("\ufeff")
    writer = csv.writer(output)
    writer.writerow([f"# Platform: {platform_name}"])
    writer.writerow([f"# Export Type: {export_type}"])
    writer.writerow([f"# Generated By: {actor_name} ({actor_role})"])
    writer.writerow([f"# Generated At: {format_export_datetime(now)}"])
    writer.writerow([f"# Total Records: {len(rows)}"])
    for label, value in (extra_metadata or []):
        writer.writerow([f"# {label}: {sanitize_cell(value)}"])
    writer.writerow([])
    writer.writerow([_title_case(column) for column in columns])
    for row in rows:
        if isinstance(row, dict):
            writer.writerow([sanitize_cell(row.get(column)) for column in columns])
        else:
            writer.writerow([sanitize_cell(value) for value in row])
    writer.writerow([])
    writer.writerow(["# End of Export"])

    response = Response(output.getvalue(), mimetype="text/csv; charset=utf-8")
    response.headers["Content-Disposition"] = f'attachment; filename="{filename}"'
    response.headers["Cache-Control"] = "no-store, no-cache"
    return response


def build_student_import_template_response(actor=None):
    settings = SettingsService.get_settings()
    platform_name = getattr(settings, "platform_name", None) or "Exam System"
    filename = f"{_safe_filename_part(platform_name)}_StudentImportTemplate.csv"
    output = StringIO()
    output.write("\ufeff")
    writer = csv.writer(output)
    writer.writerow(["# This is a blank import template. Fill in student details below."])
    writer.writerow(["# Required columns: Full Name, Email, Roll Number"])
    writer.writerow(["# Optional: Password (leave blank to auto-generate)"])
    writer.writerow(["# Do not modify the column header row."])
    writer.writerow([])
    writer.writerow(["Full Name", "Email", "Roll Number", "Password"])
    writer.writerow(["# Example: John Doe", "john@example.com", "101", "(leave blank)"])
    writer.writerow(["# Example: Asha Sen", "asha@example.com", "102", "TempPass123!"])
    writer.writerow(["# Example: Ravi Roy", "ravi@example.com", "103", "(leave blank)"])
    response = Response(output.getvalue(), mimetype="text/csv; charset=utf-8")
    response.headers["Content-Disposition"] = f'attachment; filename="{filename}"'
    response.headers["Cache-Control"] = "no-store, no-cache"
    return response
